package pl.grenczuk.metaonto;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Sat May 07 16:00:15 CEST 2022 by andrz
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#Apelacyjny
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class APELACYJNY.<p>
     * 
     */
    public static final OWLClass CLASS_APELACYJNY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#Apelacyjny"));

    /* ***************************************************
     * Class http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#Okręgowy
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OKRĘGOWY.<p>
     * 
     */
    public static final OWLClass CLASS_OKRĘGOWY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#Okręgowy"));

    /* ***************************************************
     * Class http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#Rejonowy
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REJONOWY.<p>
     * 
     */
    public static final OWLClass CLASS_REJONOWY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#Rejonowy"));

    /* ***************************************************
     * Class http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#Rodzaje_sądów
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RODZAJE_SĄDÓW.<p>
     * 
     */
    public static final OWLClass CLASS_RODZAJE_SĄDÓW = factory.getOWLClass(IRI.create("http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#Rodzaje_sądów"));

    /* ***************************************************
     * Class http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#Sąd_Najwyższy
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SĄD_NAJWYŻSZY.<p>
     * 
     */
    public static final OWLClass CLASS_SĄD_NAJWYŻSZY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#Sąd_Najwyższy"));

    /* ***************************************************
     * Class http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#Zakres_działalności_sądu
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ZAKRES_DZIAŁALNOŚCI_SĄDU.<p>
     * 
     */
    public static final OWLClass CLASS_ZAKRES_DZIAŁALNOŚCI_SĄDU = factory.getOWLClass(IRI.create("http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#Zakres_działalności_sądu"));

    /* ***************************************************
     * Class http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#Zakres_podmiotowy
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ZAKRES_PODMIOTOWY.<p>
     * 
     */
    public static final OWLClass CLASS_ZAKRES_PODMIOTOWY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#Zakres_podmiotowy"));

    /* ***************************************************
     * Class http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#Zakres_przedmiotowy
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ZAKRES_PRZEDMIOTOWY.<p>
     * 
     */
    public static final OWLClass CLASS_ZAKRES_PRZEDMIOTOWY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#Zakres_przedmiotowy"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#AdresEmail
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ADRESEMAIL.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ADRESEMAIL = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#AdresEmail"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#AdresWWW
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ADRESWWW.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ADRESWWW = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#AdresWWW"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#Adres_sądu
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ADRES_SĄDU.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ADRES_SĄDU = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#Adres_sądu"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#DaneKontaktowe
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DANEKONTAKTOWE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DANEKONTAKTOWE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#DaneKontaktowe"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#Miejscowość
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property MIEJSCOWOŚĆ.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_MIEJSCOWOŚĆ = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#Miejscowość"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#NazwaSądu
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NAZWASĄDU.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NAZWASĄDU = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#NazwaSądu"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#StatusOsoby
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property STATUSOSOBY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_STATUSOSOBY = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#StatusOsoby"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#TelefonSądu
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TELEFONSĄDU.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TELEFONSĄDU = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#TelefonSądu"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#WartośćPrzedmiotuSporu
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property WARTOŚĆPRZEDMIOTUSPORU.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_WARTOŚĆPRZEDMIOTUSPORU = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/andrz/ontologies/2021/9/PostepowanieCywilne#WartośćPrzedmiotuSporu"));


}
